version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: |
          pip install --user pep8==1.7.0 flake8==3.3.0 nose==1.3.7 pylint==1.7.1
          pip install --user -r requirements.txt
      - run:
          command: bash verify.sh
          environment:
            PATH: "/usr/bin:/bin:/sbin:/usr/local/bin:/home/circleci/.local/bin"
  markdown_lint:
    docker:
      - image: circleci/ruby:2.6-rc
    steps:
      - checkout
      - run: gem install mdl -v 0.5.0
      - run: |
          mdl README.md
          mdl CHANGELOG.md

workflows:
  version: 2
  tests:
    jobs:
      - test
      - markdown_lint
